apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend-service
    app: whatshouldieat
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 30002
  selector:
   name: frontend-pod
   app: whatshouldieat
