apiVersion: v1
kind: Service
metadata:
  name: fooditemservice-service
  labels:
    name: fooditemservice-service
    app: whatshouldieat
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: fooditemservice-pod
    app: whatshouldieat
