apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    name: frontend-deploy
    app: whatshouldieat
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend-pod
      app: whatshouldieat
  template:
    metadata:
      name: frontend-pod
      labels:
        name: frontend-pod
        app: whatshouldieat
    spec:
      containers:
      - name: frontend
        image: 383906986742.dkr.ecr.eu-central-1.amazonaws.com/whatshouldieat:frontend-74f93f03e287ee3fe5053278f479671af265e669 
        ports:
        - containerPort: 80




   
    
